---
- hosts: localhost
  connection: local
  become: yes
  vars:
    # EAP 7 as the base image
    image: registry.access.redhat.com/jboss-eap-6/eap64-openshift
    container_name: hello-eap-working-container
    image_name: hello-eap-container
  tasks:
  - name: Fetch base image and create a container out of it
    command: buildah from --name {{ container_name }} {{ image }}

  - name: Copy Application to {{ container_name }} 
    command: buildah copy --chown jboss:jboss {{ container_name }} app.war /deployments/app.war

  - name: Make Public Brodcast Ports Available For Container
    command: buildah run {{ container_name }} sh -c 'echo "JAVA_OPTS=\"\$JAVA_OPTS -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0\"" >> /opt/eap/bin/standalone.conf'

  - name: Configure {{ container_name }} Entrypoint To Be standalone.sh
    command: buildah config --entrypoint '/opt/eap/bin/standalone.sh' {{ container_name }}

  - name: Create Image from {{ container_name }} Container
    command: buildah commit {{ container_name }} {{ image_name }}

