---
- hosts: localhost
  connection: local
  become: yes
  vars:
    image_name: hello-eap-container
  tasks:
  - name: Copy {{ image_name }} to external registry
    command: skopeo copy containers-storage:localhost/{{ image_name }} {{ image_registry }}/{{ image_name }}

