---
- hosts: localhost
  connection: local
  become: yes
  vars:
    image_name: hello-eap-container
    pod_name: hello-eap-pod
  tasks:
  - name: Spin up pod to run our container
    command: podman run -d -p 8080:8080 --pod new:{{ pod_name }} --name {{ image_name }} {{ image_name }}

  - name: Ensure Pod Is Up And Running
    command: podman pod exists {{ pod_name }}
    register: result
    failed_when:
      - result.rc == 1

  - name: Generate Kubernetes Pod Definition for {{ pod_name }}
    shell: podman generate kube {{ pod_name }} > files/pod.yaml

  - name: Change Image Tag to Remote Registry
    replace:
      path: files/pod.yaml
      regexp: "localhost/{{ image_name }}"
      replace: "{{ image_registry }}/{{ image_name }}"
