apiVersion: v1
kind: Service
metadata:
  name: hello-eap 
spec:
  selector:                  
    app: hello-eap-pod
  ports:
  - nodePort: 0
    port: 8080         
    protocol: TCP
    targetPort: 8080
